Update version of codeql-analysis.yml
mingrammer/diagrams pull request #1035
Opened 2024-10-26 09:12 UTC by tvqphuoc01

codeQL v1 is deprecated so we should upgrade to v2: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

2024-10-28 11:47 UTC, gabriel-tessier requested changes

2024-10-28 11:47 UTC, gabriel-tessier commented on .github/workflows/codeql-analysis.yml
>        with:
Look like v4 is the latest:

https://github.com/actions/checkout

2024-10-28 11:49 UTC, gabriel-tessier commented
Maybe we can use dependabot to keep actions up to date.

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

2024-10-30 07:54 UTC, tvqphuoc01 commented
@gabriel-tessier seem like we don't have permission to config dependabot 🤔

2024-10-30 10:48 UTC, gabriel-tessier commented
> @gabriel-tessier seem like we don't have permission to config dependabot 🤔

Thanks for sharing about dependabot, it's not really a big a deal, we can always do it manually if it change one time each n years.

2024-10-31 10:15 UTC, gabriel-tessier commented
@tvqphuoc01 
In the first review I commented about the latest checkout version that is now v4. You marked my comment as resolved but I still see v3 and there's no new commit.
Did I mess something or there's a reason to stick with v3?

2024-11-06 00:32 UTC, gabriel-tessier approved these changes

2024-11-06 03:41 UTC, mingrammer approved these changes

2024-11-06 03:43 UTC, merged