Add diagrams.onprem.network.CiscoRouter, CiscoRouterL2, CiscoRouterL3
mingrammer/diagrams pull request #1060
Opened 2024-11-18 04:56 UTC by nobiit

Add diagrams.onprem.network.CiscoRouter
Add diagrams.onprem.network.CiscoRouterL2
Add diagrams.onprem.network.CiscoRouterL3

2025-07-20 09:21 UTC, gabriel-tessier requested changes
@nobiit 

Thank you for your contribution and sorry for the late review, I left one comment if you can check about. It should be fine after that to merge the PR.

2025-07-20 09:21 UTC, gabriel-tessier commented on resources/onprem/network/cisco-router.png
@nobiit 

Can you you update this icon, by replacing the white background with alpha so it can render as a round in the diagrams.

2025-07-20 10:25 UTC, gabriel-tessier approved these changes
@nobiit 
Great and fast work. Thank you again.

2025-07-21 05:18 UTC, filipeaaoliveira approved these changes

2025-07-22 11:31 UTC, merged