Features/pve lxc java dns zabbix
mingrammer/diagrams pull request #291
Opened 2020-09-22 16:33 UTC by bemanuel

Merge of branches (Zabbix,LXC, PVE, etc...), correction of outscale and UPPER_WORDS ( lxc and pve )

2020-09-23 05:50 UTC, wolfspyre reviewed
FWIW, I love seeing proxmox represented. 😀 i could see the value in an example, but I don’t know that it’s necessary (or even desired)... Regardless i’d love to see this merged

2020-09-25 02:38 UTC, mingrammer commented
Please resolve the conflict

2020-09-25 17:48 UTC, bemanuel commented
> FWIW, I love seeing proxmox represented.  i could see the value in an example, but I don’t know that it’s necessary (or even desired)... Regardless i’d love to see this merged

I'm a huge user from Proxmox and always try to help.

2020-09-26 07:40 UTC, mingrammer requested changes

2020-09-26 07:40 UTC, mingrammer commented on config.py
> +            "ProxmoxVE": "PVE",
It should be `"Pve": "ProxmoxVE",` and need to rerun `autogen.sh` to update alias for proxmox. This might be the last request change.

2020-09-29 07:33 UTC, mingrammer approved these changes
LGTM. Thank you!

2020-09-29 07:34 UTC, merged

2020-10-09 04:27 UTC, zqfan commented
this pr has wrong config.py content, which can be fixed by: https://github.com/mingrammer/diagrams/pull/345