feat(scripts): provide `diagrams` CLI
mingrammer/diagrams pull request #524
Opened 2021-05-01 11:17 UTC by m1racoli

This changes addresses https://github.com/mingrammer/diagrams/issues/369 while providing a simple CLI entry point which can be used outside the virtual environment of the installed package.

This works well with for example with [pipx](https://pipxproject.github.io/pipx/).

2021-05-03 07:26 UTC, m1racoli commented
@mingrammer Let me know, what you think about this PR :)

2021-05-04 04:54 UTC, gabriel-tessier commented
@m1racoli 
Great job, this feature was missing! 
But what about returning the name of the file(s) generated instead of 0 which can be useful if you use another tool to communicate and for unit test!

One remark about the code:

You defined  nargs="+", and you loop trough all the paths so it's mean that you can call with several files.
`$ diagrams diagram1.py diagram2.py `
which is good but if you can add a line about in the doc, it can be better!

@mingrammer WDYT

2021-05-04 07:09 UTC, m1racoli commented
@gabriel-tessier 
> But what about returning the name of the file(s) generated instead of 0 which can be useful if you use another tool to communicate and for unit test!

Good point. I can print a list of processed python files to stdout. Later on this would be very useful, if we'd process directories. But I would keep the `exit(0)` since that's a signal for success. Any other exit code could be enabled via a flag later on. What could be difficult, is to retrieve the list of generated image files from within the context of the executing script.

> You defined nargs="+", and you loop trough all the paths so it's mean that you can call with several files.
$ diagrams diagram1.py diagram2.py
which is good but if you can add a line about in the doc, it can be better!

Yes, makes sense! Will do.

I'll amend my changes to the existing commit and force push, if that's ok for you.

2024-12-28 08:01 UTC, foursixnine commented
Hi! I just followed instructions, but used pipx instead of i.e poetry, and got to this particular PR:

```
foursixnine@pakhet ~ % diagrams diagram.py
Traceback (most recent call last):
  File "/Users/foursixnine/.local/bin/diagrams", line 5, in <module>
    from diagrams.cli import main
ModuleNotFoundError: No module named 'diagrams.cli'
```

the following worked for me:
- brew install graphviz
- poetry new diagrams-poetry
-  cd diagrams-poetry
- poetry add diagrams
- poetry run  python  ~/diagram.py (contents from: https://diagrams.mingrammer.com/docs/getting-started/installation#quick-start)
- open web_service.png

Perhaps something else would allow me to run it without a workaround for poetry and use directly pipx?

2025-03-10 07:28 UTC, mingrammer commented
@m1racoli Is this still in progress?

2025-03-10 19:14 UTC, m1racoli commented
> @m1racoli Is this still in progress?

Hey, it's open for review. :)

2025-03-11 06:36 UTC, mingrammer commented
@gabriel-tessier Hi, we should consider this PR too.

2025-03-16 11:59 UTC, gabriel-tessier commented
@m1racoli 
I tried to resynch your branch on upstream master but the branch is pretty old and get too much conflicts.
If you can start a new branch from master and cherry pick your changes it should be better.

Sorry for the mess with the branch.

2025-03-16 17:57 UTC, m1racoli commented
Hehe, no worries. Let me take a look next week.

2025-03-17 08:02 UTC, mingrammer commented
Thank you all guys!

2025-03-20 03:46 UTC, m1racoli commented
So, should be good to go.

2025-03-21 09:25 UTC, gabriel-tessier requested changes
better to open another PR with the uv related changes in the installation doc as it's not related with the cli changes.

2025-03-21 09:34 UTC, gabriel-tessier commented
@m1racoli 
Thank you again for the PR. 
I added docstring and set utf-8 in the open file call, I also removed the print in the path loop.
I added a unit test file can you check if there's missing cases.
And last one can you remove the line related to 'uv' in the installation file, you can create a new PR for this change as it's not related to the CLI changes.

Sorry for the asks and thanks again for your contribution.
Sorry for the 3 years delay, I hope we will merge it before next week so we will not reach 4 years delay 😅.

2025-03-21 09:53 UTC, filipeaaoliveira approved these changes

2025-04-21 07:57 UTC, mingrammer commented
Could you please check the pre-commit status?

2025-05-03 16:11 UTC, gabriel-tessier commented
Sorry for the late check, I run the pre-commit on local and pushed, it solved the first problem but somehow a new error raise.
On my local all pre-commit check pass, if somebody know how to solve this, you are more than welcome.

2025-05-06 04:20 UTC, mingrammer commented
I checked the error message, but it seems not critical error message (actually it is not "error"), so I think we can just merge this feature regardless of failed pre-commit.

2025-05-10 01:29 UTC, gabriel-tessier approved these changes

2025-05-10 01:32 UTC, gabriel-tessier commented
> I checked the error message, but it seems not critical error message (actually it is not "error"), so I think we can just merge this feature regardless of failed pre-commit.

Yes it's just formatting problem and look like the changes are not on this branch but on master. I will run again pre-commit on master and try to push a fix otherwise we will bump again for the next PRs.

2025-05-10 01:33 UTC, merged