Added DigitalOcean provider
mingrammer/diagrams pull request #621
Opened 2021-11-15 14:22 UTC by mandalae

I've added assets and a provider for DigitalOcean.

I tried to follow the development and contribution guides, but if I've done anything wrong, please let me know.

2021-11-18 14:39 UTC, mandalae commented
@mingrammer Is there any way to get this reviewed? I notice that there are quite a lot of PRs outstanding, so I'm wondering if this is still actively being worked on?

2022-01-21 15:09 UTC, mingrammer requested changes
Plz check the azure config.

2022-01-21 15:09 UTC, mingrammer commented on config.py
> +    "azure": ("vpn", "vpc"),
"azure" key is duplicated.

2022-01-21 15:09 UTC, mingrammer commented
Sorry for the late reply. @mandalae

2022-01-21 15:17 UTC, mandalae commented on config.py
> +    "azure": ("vpn", "vpc"),
Fixed :)

2022-01-21 15:17 UTC, mandalae commented
Thanks for reviewing, I've fixed that comment now :)

2022-01-21 15:18 UTC, mingrammer commented
@mandalae Please re-run the autogen script!

2022-01-21 15:23 UTC, mandalae commented
@mingrammer  Done, a lot of the changes in this PR came from doing that in the first place I think. I only really added the DO stuff, I never meant to change anything in AWS or Azure.

2022-01-22 04:04 UTC, mingrammer approved these changes
LGTM!. Thank you for working on it.

2022-01-22 04:05 UTC, merged

2022-01-22 05:17 UTC, mingrammer commented
v0.21.0 is now released.

2022-02-05 21:10 UTC, dajor commented
Is in the last version not a __init__.py missing for DigitalOcean?

2022-02-06 14:52 UTC, mandalae commented
Correct @dajor I've added it in this PR: https://github.com/mingrammer/diagrams/pull/646 :) - Thanks for pointing it out.

2022-02-06 15:13 UTC, dajor commented
There is one more bug:

from diagrams import Diagram

from diagrams.digitalocean.network import LoadBalancer
from diagrams.digitalocean.storage import Space

from diagrams.digitalocean.compute import Containers


with Diagram("Test", show=False):
    LoadBalancer >> Containers >> Space


Traceback (most recent call last):
    Containers >> Space
TypeError: unsupported operand type(s) for >>: 'type' and 'type'