Add new provider GIS
mingrammer/diagrams pull request #847
Opened 2023-02-05 17:31 UTC by AlexGacon

I am starting this new provider to gather all GIS (Geographical Information System) related nodes.

2023-02-05 17:31 UTC, AlexGacon commented
I also took the opportunity to update the contribution documentation in order to describe what must be done to add a new provider.

2023-10-11 03:47 UTC, AlexGacon commented
@mingrammer any chance to have it integrated?

2025-01-13 12:22 UTC, gabriel-tessier requested changes
Just small fixes:

- [ ] rename the file gis/routing/osmr.png --- > should be osrm.png
- [ ] gis/server/mapserver height is over 256, must be 256 max. 
- [ ] re-run autogen

2025-01-13 12:50 UTC, AlexGacon commented
@gabriel-tessier I just applied all your suggestions.

2025-01-15 06:27 UTC, AlexGacon commented
@tvqphuoc01 hello! I just pushed the asked changes.

2025-01-15 11:25 UTC, gabriel-tessier requested changes
Sorry again to asking changes.
I left copy paste comments... 
- There's files that are too big.
- There's one file CAS in resources that is not related with nothing.
- There's 2 certbot and openLdap that are not related with GIS.

Better to have only the changes for GIS provider in this PR.
You can open new PR for the on premise icons.

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/cas.png
what is this file?

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/gis/cli/mdal.png
size don't match

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/gis/desktop/maptunik.png
size don't match

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/gis/geocoding/pelias.png
size don't match

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/gis/mobile/smash.png
size don't match

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/gis/server/kepler.png
size don't match

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/gis/server/mapserver.png
ok!

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/onprem/certificates/certbot.png
This one is not related with GIS provider if you want to add it and you should add it make a different PR with only this file.

2025-01-15 11:25 UTC, gabriel-tessier commented on resources/openldap.png
This one is not related with GIS provider if you want to add it and you should add it make a different PR with only this file.

2025-01-15 11:36 UTC, AlexGacon commented
Hi I will take care of it tomorrow!

Le mer. 15 janv. 2025, 12:29, gabriel-tessier ***@***.***> a
écrit :

> @AlexGacon <https://github.com/AlexGacon> @tvqphuoc01
> <https://github.com/tvqphuoc01>
>
> Just another comment, the icon mapnik is in the cplusplus section, what
> about move it to 'toolkit' that is more generic name.
> As cplusplus is a language and if they rewrite it in Rust it will no more
> be correct.
>
> I found the name 'toolkit' when I searched mapnik on wikipedia!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mingrammer/diagrams/pull/847#issuecomment-2592452637>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXE4XMSHFGAJHPA5OH5R432KZBC5AVCNFSM6AAAAABVCOVG5CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOJSGQ2TENRTG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-15 12:20 UTC, AlexGacon commented
@gabriel-tessier regarding mapnik, I have a folder "CLI" which can be seen as toolkit too. Should I rename it "toolkit" or move mapnik into "cli"?

2025-01-15 12:21 UTC, AlexGacon commented on resources/onprem/certificates/certbot.png
agreed and solved

2025-01-15 12:31 UTC, AlexGacon commented
@gabriel-tessier I just pushed the asked changes. It was in progress work I didn't track correctly. Sorry for the work.

2025-01-18 11:20 UTC, gabriel-tessier commented
> @gabriel-tessier regarding mapnik, I have a folder "CLI" which can be seen as toolkit too. Should I rename it "toolkit" or move mapnik into "cli"?

Let's put it 'cli' with other nodes.

2025-01-18 11:22 UTC, gabriel-tessier approved these changes
@AlexGacon 
All good. 
If you have time to move mapnik in 'cli' it's ok if you don't time it's will be also ok, it's not blocking.

I may ask you later an icon for GIS something like a global icon for the provider. It's related to this PR:
https://github.com/mingrammer/diagrams/pull/1039

As you pushed a new documentation to add a provider I will update it with instruction to add a top icon for the provider.
I ask again but if it's ok for you I will assign you the issue, I will prepare it before the end of the month.

Thanks again for your contribution.

2025-01-18 14:03 UTC, AlexGacon commented
@gabriel-tessier changes done

2025-01-20 12:52 UTC, AlexGacon commented
@gabriel-tessier should I change something to pass the pre-commit check?

2025-02-02 07:28 UTC, gabriel-tessier commented
@AlexGacon Sorry for the delay, the pre-commit failure is not related with your changes so it's ok to ignore it.

Thank you again for the PR and the fixes.

2025-02-02 07:28 UTC, merged